const types = {
  FETCH_AUTOCOMPLETE: "FETCH_AUTOCOMPLETE",
  FETCH_CURRENTWEATHER: "FETCH_CURRENTWEATHER",
  FETCH_FORECAST: "FETCH_FORECAST",
  SET_CURRENTCITY: "SET_CURRENTCITY",
  FETCH_FAVORITES: "FETCH_FAVORITES",
  TOGGLE_FAVORITE: " TOGGLE_FAVORITE",
};
export default types;
